version: "3.9"

services:
  web:
    build: .
    container_name: marketlink_web
    command: gunicorn marketlink.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - marketlink_network

  celery:
    build: .
    container_name: marketlink_celery
    command: celery -A marketlink worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
    networks:
      - marketlink_network

  redis:
    image: redis:7-alpine
    container_name: marketlink_redis
    ports:
      - "6379:6379"
    networks:
      - marketlink_network

networks:
  marketlink_network:
    driver: bridge
